// Canonical Default Course Fee Rates matching ThoughtFlows Master Fee Sheet (INR Converted)

export const DEFAULT_COURSE_FEE_RATES = [
  // 1. CPC Certification Programmes
  {
    code: 'CPC',
    name: 'CPC – Certified Professional Coder',
    category: 'CPC Certification Programmes',
    duration: '45 DAYS',
    oldFee: 12000,
    newFeeNoDiscount: 15000,
    standardFee: 15000,
    originalFee: 12000,
    courseFee: 14000,
    trainingFee: 14000,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: '₹70,207 ($814.20 + ₹1k tx fees)',
    examFee: 70207,
    gstPercent: 18,
    maxDiscount: 1000,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 14000
  },
  {
    code: 'CPC Fast track',
    name: 'CPC Fast Track',
    category: 'CPC Certification Programmes',
    duration: '30 Days',
    oldFee: 10000,
    newFeeNoDiscount: 13000,
    standardFee: 13000,
    originalFee: 10000,
    courseFee: 11500,
    trainingFee: 11500,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: '₹70,207 ($814.20 + ₹1k tx fees)',
    examFee: 70207,
    gstPercent: 18,
    maxDiscount: 1500,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 11500
  },
  {
    code: 'CPC+ED',
    name: 'CPC + ED (Emergency Department)',
    category: 'CPC Certification Programmes',
    duration: '2 Months',
    oldFee: 18000,
    newFeeNoDiscount: 23000,
    standardFee: 23000,
    originalFee: 18000,
    courseFee: 21000,
    trainingFee: 21000,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: '₹70,207 ($814.20 + ₹1k tx fees)',
    examFee: 70207,
    gstPercent: 18,
    maxDiscount: 2000,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 21000
  },
  {
    code: 'CPC+E/M',
    name: 'CPC + E/M (Evaluation & Management)',
    category: 'CPC Certification Programmes',
    duration: '2 Months',
    oldFee: 18000,
    newFeeNoDiscount: 23000,
    standardFee: 23000,
    originalFee: 18000,
    courseFee: 21000,
    trainingFee: 21000,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: '₹70,207 ($814.20 + ₹1k tx fees)',
    examFee: 70207,
    gstPercent: 18,
    maxDiscount: 2000,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 21000
  },

  // 2. Inpatient Training programmes
  {
    code: 'CIC for freshers',
    name: 'CIC for Freshers',
    category: 'Inpatient Training programmes',
    duration: '2 Months',
    oldFee: 25000,
    newFeeNoDiscount: 30000,
    standardFee: 30000,
    originalFee: 25000,
    courseFee: 29000,
    trainingFee: 29000,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: '₹71,230 ($838 USD)',
    examFee: 71230,
    gstPercent: 18,
    maxDiscount: 1000,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 29000
  },
  {
    code: 'CIC (Exp in IPDRG)',
    name: 'CIC (If candidate has experience in IPDRG)',
    category: 'Inpatient Training programmes',
    duration: '2 Months',
    oldFee: 18000,
    newFeeNoDiscount: 23000,
    standardFee: 23000,
    originalFee: 18000,
    courseFee: 21000,
    trainingFee: 21000,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: '₹71,230 ($838 USD)',
    examFee: 71230,
    gstPercent: 18,
    maxDiscount: 2000,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 21000
  },
  {
    code: 'IP-DRG',
    name: 'IP-DRG (Inpatient Diagnosis Related Groups)',
    category: 'Inpatient Training programmes',
    duration: '45 DAYS',
    oldFee: 15000,
    newFeeNoDiscount: 20000,
    standardFee: 20000,
    originalFee: 15000,
    courseFee: 17500,
    trainingFee: 17500,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: 'NO EXAM',
    examFee: 0,
    gstPercent: 18,
    maxDiscount: 2500,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 17500
  },
  {
    code: 'CIC Fast Track',
    name: 'CIC Fast Track',
    category: 'Inpatient Training programmes',
    duration: '30 Days',
    oldFee: 10000,
    newFeeNoDiscount: 12000,
    standardFee: 12000,
    originalFee: 10000,
    courseFee: 10000,
    trainingFee: 10000,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: 'No booking',
    examFee: 0,
    gstPercent: 18,
    maxDiscount: 2000,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 10000
  },
  {
    code: 'CCS',
    name: 'CCS – Certified Coding Specialist (AHIMA)',
    category: 'Inpatient Training programmes',
    duration: '45 Days',
    oldFee: 25000,
    newFeeNoDiscount: 30000,
    standardFee: 30000,
    originalFee: 25000,
    courseFee: 29000,
    trainingFee: 29000,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: '₹33,915 ($399 USD)',
    examFee: 33915,
    gstPercent: 18,
    maxDiscount: 1000,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 29000
  },
  {
    code: 'CCS (Exp in IPDRG)',
    name: 'CCS (If candidate has experience in IPDRG)',
    category: 'Inpatient Training programmes',
    duration: '45 Days',
    oldFee: 18000,
    newFeeNoDiscount: 23000,
    standardFee: 23000,
    originalFee: 18000,
    courseFee: 21000,
    trainingFee: 21000,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: '₹33,915 ($399 USD)',
    examFee: 33915,
    gstPercent: 18,
    maxDiscount: 2000,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 21000
  },
  {
    code: 'CIC + IP Specialty',
    name: 'CIC + IP Specialty',
    category: 'Inpatient Training programmes',
    duration: '2 Months',
    oldFee: 25000,
    newFeeNoDiscount: 30000,
    standardFee: 30000,
    originalFee: 25000,
    courseFee: 29000,
    trainingFee: 29000,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: '₹71,230 ($838 USD)',
    examFee: 71230,
    gstPercent: 18,
    maxDiscount: 1000,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 29000
  },
  {
    code: 'CCS + IP Specialty',
    name: 'CCS + IP Specialty',
    category: 'Inpatient Training programmes',
    duration: '2 Months',
    oldFee: 25000,
    newFeeNoDiscount: 30000,
    standardFee: 30000,
    originalFee: 25000,
    courseFee: 29000,
    trainingFee: 29000,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: '₹33,915 ($399 USD)',
    examFee: 33915,
    gstPercent: 18,
    maxDiscount: 1000,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 29000
  },
  {
    code: 'CPC+CIC',
    name: 'CPC + CIC (Fresher progression without anatomy)',
    category: 'Inpatient Training programmes',
    duration: '3 Months',
    oldFee: 35000,
    newFeeNoDiscount: 40000,
    standardFee: 40000,
    originalFee: 35000,
    courseFee: 35000,
    trainingFee: 35000,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: 'AAPC / AHIMA Vouchers',
    examFee: 70207,
    gstPercent: 18,
    maxDiscount: 5000,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 35000
  },

  // 3. Outpatient Training programme
  {
    code: 'COC',
    name: 'COC – Certified Outpatient Coder',
    category: 'Outpatient Training programme',
    duration: '45 DAYS',
    oldFee: 12000,
    newFeeNoDiscount: 15000,
    standardFee: 15000,
    originalFee: 12000,
    courseFee: 14000,
    trainingFee: 14000,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: '₹72,230 ($838 + ₹1k tx fees)',
    examFee: 72230,
    gstPercent: 18,
    maxDiscount: 1000,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 14000
  },

  // 4. Surgery Training programme
  {
    code: 'Surgery',
    name: 'Surgery Specialty Coding',
    category: 'Surgery Training programme',
    duration: '45 DAYS',
    oldFee: 15000,
    newFeeNoDiscount: 20000,
    standardFee: 20000,
    originalFee: 15000,
    courseFee: 17500,
    trainingFee: 17500,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: 'NO EXAM',
    examFee: 0,
    gstPercent: 18,
    maxDiscount: 2500,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 17500
  },
  {
    code: 'CGSC',
    name: 'CGSC – Certified General Surgery Coder',
    category: 'Surgery Training programme',
    duration: '60 Days',
    oldFee: 20000,
    newFeeNoDiscount: 25000,
    standardFee: 25000,
    originalFee: 20000,
    courseFee: 23500,
    trainingFee: 23500,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: '₹72,230 ($838 + ₹1k tx fees)',
    examFee: 72230,
    gstPercent: 18,
    maxDiscount: 1500,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 23500
  },

  // 5. Auditing Training programme
  {
    code: 'CPMA',
    name: 'CPMA – Certified Professional Medical Auditor',
    category: 'Auditing Training programme',
    duration: '45 DAYS',
    oldFee: 15000,
    newFeeNoDiscount: 20000,
    standardFee: 20000,
    originalFee: 15000,
    courseFee: 17500,
    trainingFee: 17500,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: '₹72,230 ($838 + ₹1k tx fees)',
    examFee: 72230,
    gstPercent: 18,
    maxDiscount: 2500,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 17500
  },

  // 6. E/M and ED Training programmes
  {
    code: 'ED',
    name: 'ED – Emergency Department Coding',
    category: 'E/M and ED Training programmes',
    duration: '20 Days',
    oldFee: 7000,
    newFeeNoDiscount: 10000,
    standardFee: 10000,
    originalFee: 7000,
    courseFee: 8000,
    trainingFee: 8000,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: 'NO EXAM',
    examFee: 0,
    gstPercent: 18,
    maxDiscount: 2000,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 8000
  },
  {
    code: 'E/M',
    name: 'E/M – Evaluation and Management',
    category: 'E/M and ED Training programmes',
    duration: '20 Days',
    oldFee: 7000,
    newFeeNoDiscount: 10000,
    standardFee: 10000,
    originalFee: 7000,
    courseFee: 8000,
    trainingFee: 8000,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: 'NO EXAM',
    examFee: 0,
    gstPercent: 18,
    maxDiscount: 2000,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 8000
  },
  {
    code: 'ED&E/M',
    name: 'ED & E/M Combined Training',
    category: 'E/M and ED Training programmes',
    duration: '30 Days',
    oldFee: 13000,
    newFeeNoDiscount: 17000,
    standardFee: 17000,
    originalFee: 13000,
    courseFee: 15000,
    trainingFee: 15000,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: 'NO EXAM',
    examFee: 0,
    gstPercent: 18,
    maxDiscount: 2000,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 15000
  },
  {
    code: 'ED Profee',
    name: 'ED Profee (Professional Fee Coding)',
    category: 'E/M and ED Training programmes',
    duration: '10 days',
    oldFee: 3500,
    newFeeNoDiscount: 5000,
    standardFee: 5000,
    originalFee: 3500,
    courseFee: 4000,
    trainingFee: 4000,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: 'NO EXAM',
    examFee: 0,
    gstPercent: 18,
    maxDiscount: 1000,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 4000
  },
  {
    code: 'ED Facility',
    name: 'ED Facility Coding',
    category: 'E/M and ED Training programmes',
    duration: '10 days',
    oldFee: 3500,
    newFeeNoDiscount: 5000,
    standardFee: 5000,
    originalFee: 3500,
    courseFee: 4000,
    trainingFee: 4000,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: 'NO EXAM',
    examFee: 0,
    gstPercent: 18,
    maxDiscount: 1000,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 4000
  },
  {
    code: 'EM IP & OP',
    name: 'E/M Inpatient & Outpatient',
    category: 'E/M and ED Training programmes',
    duration: '30 Days',
    oldFee: 10000,
    newFeeNoDiscount: 13000,
    standardFee: 13000,
    originalFee: 10000,
    courseFee: 11500,
    trainingFee: 11500,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: 'NO EXAM',
    examFee: 0,
    gstPercent: 18,
    maxDiscount: 1500,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 11500
  },
  {
    code: 'CEDC',
    name: 'CEDC – Certified Emergency Department Coder',
    category: 'E/M and ED Training programmes',
    duration: '45 Days',
    oldFee: 18000,
    newFeeNoDiscount: 23000,
    standardFee: 23000,
    originalFee: 18000,
    courseFee: 21000,
    trainingFee: 21000,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: '₹72,230 ($838 + ₹1k tx fees)',
    examFee: 72230,
    gstPercent: 18,
    maxDiscount: 2000,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 21000
  },
  {
    code: 'CEMC',
    name: 'CEMC – Certified Evaluation & Management Coder',
    category: 'E/M and ED Training programmes',
    duration: '45 Days',
    oldFee: 18000,
    newFeeNoDiscount: 23000,
    standardFee: 23000,
    originalFee: 18000,
    courseFee: 21000,
    trainingFee: 21000,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: '₹72,230 ($838 + ₹1k tx fees)',
    examFee: 72230,
    gstPercent: 18,
    maxDiscount: 2000,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 21000
  },

  // 7. Risk Adjustment Training Programmes
  {
    code: 'HCC',
    name: 'HCC Risk Adjustment Coding',
    category: 'Risk Adjustment Training Programmes',
    duration: '30 days',
    oldFee: 10000,
    newFeeNoDiscount: 13000,
    standardFee: 13000,
    originalFee: 10000,
    courseFee: 11500,
    trainingFee: 11500,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: 'NO EXAM',
    examFee: 0,
    gstPercent: 18,
    maxDiscount: 1500,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 11500
  },
  {
    code: 'CRC',
    name: 'CRC – Certified Risk Adjustment Coder',
    category: 'Risk Adjustment Training Programmes',
    duration: '45 Days',
    oldFee: 12000,
    newFeeNoDiscount: 15000,
    standardFee: 15000,
    originalFee: 12000,
    courseFee: 14000,
    trainingFee: 14000,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: '₹72,230 ($838 + ₹1k tx fees)',
    examFee: 72230,
    gstPercent: 18,
    maxDiscount: 1000,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 14000
  },

  // 8. Other Training Programmes
  {
    code: 'IVR Specialty',
    name: 'Interventional Radiology Specialty',
    category: 'Other Training Programmes',
    duration: '20 days',
    oldFee: 15000,
    newFeeNoDiscount: 20000,
    standardFee: 20000,
    originalFee: 15000,
    courseFee: 17500,
    trainingFee: 17500,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: 'NO EXAM',
    examFee: 0,
    gstPercent: 18,
    maxDiscount: 2500,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 17500
  },
  {
    code: 'Radiology',
    name: 'Radiology Specialty Coding',
    category: 'Other Training Programmes',
    duration: '20-25 days',
    oldFee: 15000,
    newFeeNoDiscount: 20000,
    standardFee: 20000,
    originalFee: 15000,
    courseFee: 17500,
    trainingFee: 17500,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: 'NO EXAM',
    examFee: 0,
    gstPercent: 18,
    maxDiscount: 2500,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 17500
  },
  {
    code: 'Anesthesia',
    name: 'Anesthesia Specialty Coding',
    category: 'Other Training Programmes',
    duration: '30 days',
    oldFee: 10000,
    newFeeNoDiscount: 13000,
    standardFee: 13000,
    originalFee: 10000,
    courseFee: 11500,
    trainingFee: 11500,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: 'NO EXAM',
    examFee: 0,
    gstPercent: 18,
    maxDiscount: 1500,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 11500
  },
  {
    code: 'CPB',
    name: 'CPB – Certified Professional Biller',
    category: 'Other Training Programmes',
    duration: '45 Days',
    oldFee: 15000,
    newFeeNoDiscount: 20000,
    standardFee: 20000,
    originalFee: 15000,
    courseFee: 17500,
    trainingFee: 17500,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: '₹72,230 ($838 + ₹1k tx fees)',
    examFee: 72230,
    gstPercent: 18,
    maxDiscount: 2500,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 17500
  },
  {
    code: 'Anatomy Alone',
    name: 'Medical Anatomy Alone',
    category: 'Other Training Programmes',
    duration: '15 Days',
    oldFee: 7000,
    newFeeNoDiscount: 9000,
    standardFee: 9000,
    originalFee: 7000,
    courseFee: 8000,
    trainingFee: 8000,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: 'NO EXAM',
    examFee: 0,
    gstPercent: 18,
    maxDiscount: 1000,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 8000
  },
  {
    code: 'CPT Alone',
    name: 'CPT Coding Alone',
    category: 'Other Training Programmes',
    duration: '20 Days',
    oldFee: 7000,
    newFeeNoDiscount: 9000,
    standardFee: 9000,
    originalFee: 7000,
    courseFee: 8000,
    trainingFee: 8000,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: 'NO EXAM',
    examFee: 0,
    gstPercent: 18,
    maxDiscount: 1000,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 8000
  },
  {
    code: 'ICD Alone',
    name: 'ICD-10-CM Alone',
    category: 'Other Training Programmes',
    duration: '15 Days',
    oldFee: 7000,
    newFeeNoDiscount: 9000,
    standardFee: 9000,
    originalFee: 7000,
    courseFee: 8000,
    trainingFee: 8000,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: 'NO EXAM',
    examFee: 0,
    gstPercent: 18,
    maxDiscount: 1000,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 8000
  },
  {
    code: 'Anatomy + PCS',
    name: 'Anatomy + ICD-10-PCS Combined',
    category: 'Other Training Programmes',
    duration: '30 Days',
    oldFee: 15000,
    newFeeNoDiscount: 18000,
    standardFee: 18000,
    originalFee: 15000,
    courseFee: 17000,
    trainingFee: 17000,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: 'NO EXAM',
    examFee: 0,
    gstPercent: 18,
    maxDiscount: 1000,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 17000
  },
  {
    code: 'Anatomy + CCS',
    name: 'Anatomy + CCS Track',
    category: 'Other Training Programmes',
    duration: '45 Days',
    oldFee: 27000,
    newFeeNoDiscount: 27000,
    standardFee: 27000,
    originalFee: 27000,
    courseFee: 25000,
    trainingFee: 25000,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: '₹33,915 ($399 USD)',
    examFee: 33915,
    gstPercent: 18,
    maxDiscount: 2000,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 25000
  },
  {
    code: 'PCS Alone',
    name: 'ICD-10-PCS Alone',
    category: 'Other Training Programmes',
    duration: '20 Days',
    oldFee: 10000,
    newFeeNoDiscount: 13000,
    standardFee: 13000,
    originalFee: 10000,
    courseFee: 11500,
    trainingFee: 11500,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: 'NO EXAM',
    examFee: 0,
    gstPercent: 18,
    maxDiscount: 1500,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 11500
  },
  {
    code: 'AR calling (with billing)',
    name: 'AR Calling (With Billing)',
    category: 'Other Training Programmes',
    duration: '30 Days',
    oldFee: 12000,
    newFeeNoDiscount: 15000,
    standardFee: 15000,
    originalFee: 12000,
    courseFee: 13500,
    trainingFee: 13500,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: 'NO EXAM',
    examFee: 0,
    gstPercent: 18,
    maxDiscount: 1500,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 13500
  },
  {
    code: 'AR calling (Without billing)',
    name: 'AR Calling (Without Billing)',
    category: 'Other Training Programmes',
    duration: '20 Days',
    oldFee: 8000,
    newFeeNoDiscount: 11000,
    standardFee: 11000,
    originalFee: 8000,
    courseFee: 9500,
    trainingFee: 9500,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: 'NO EXAM',
    examFee: 0,
    gstPercent: 18,
    maxDiscount: 1500,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 9500
  },
  {
    code: 'CPT + HCPCS',
    name: 'CPT + HCPCS (without ICD)',
    category: 'Other Training Programmes',
    duration: '25 Days',
    oldFee: 10000,
    newFeeNoDiscount: 13000,
    standardFee: 13000,
    originalFee: 10000,
    courseFee: 11500,
    trainingFee: 11500,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: 'NO EXAM',
    examFee: 0,
    gstPercent: 18,
    maxDiscount: 1500,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 11500
  },
  {
    code: 'SDS',
    name: 'SDS – Same Day Surgery',
    category: 'Other Training Programmes',
    duration: '25 to 30 days',
    oldFee: 10000,
    newFeeNoDiscount: 13000,
    standardFee: 13000,
    originalFee: 10000,
    courseFee: 11500,
    trainingFee: 11500,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: 'NO EXAM',
    examFee: 0,
    gstPercent: 18,
    maxDiscount: 1500,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 11500
  },
  {
    code: 'Home Health Coding',
    name: 'Home Health Coding',
    category: 'Other Training Programmes',
    duration: '30 Days',
    oldFee: 10000,
    newFeeNoDiscount: 15000,
    standardFee: 15000,
    originalFee: 10000,
    courseFee: 13000,
    trainingFee: 13000,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: 'NO EXAM',
    examFee: 0,
    gstPercent: 18,
    maxDiscount: 2000,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 13000
  },
  {
    code: 'Anesthesia+CCS(Fresher)',
    name: 'Anesthesia + CCS (Fresher)',
    category: 'Other Training Programmes',
    duration: '60 Days',
    oldFee: 28000,
    newFeeNoDiscount: 33000,
    standardFee: 33000,
    originalFee: 28000,
    courseFee: 31000,
    trainingFee: 31000,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: '₹33,915 ($399 USD)',
    examFee: 33915,
    gstPercent: 18,
    maxDiscount: 2000,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 31000
  },
  {
    code: 'Anesthesia+CCS(Exp)',
    name: 'Anesthesia + CCS (Exp in IPDRG)',
    category: 'Other Training Programmes',
    duration: '45 Days',
    oldFee: 22000,
    newFeeNoDiscount: 26000,
    standardFee: 26000,
    originalFee: 22000,
    courseFee: 24000,
    trainingFee: 24000,
    registrationFee: 0,
    studyMaterialFee: 0,
    membershipFee: 0,
    examFeeText: '₹33,915 ($399 USD)',
    examFee: 33915,
    gstPercent: 18,
    maxDiscount: 2000,
    installments: 'Full / Installment options available',
    currency: 'INR',
    totalPayable: 24000
  }
];
