// Qualification options grouped for lead / registration forms.
export const QUALIFICATION_GROUPS = [
  {
    group: 'life',
    title: 'Life Science',
    options: [
      'MBBS',
      'BDS (Dental)',
      'BAMS / BHMS / BSMS / BUMS / BNYS (AYUSH)',
      'BPharm (Bachelor of Pharmacy)',
      'DPharm (Diploma in Pharmacy)',
      'MPharm / PharmD',
      'BSc Nursing',
      'GNM / ANM (Nursing Diploma)',
      'MSc Nursing',
      'BPT (Physiotherapy)',
      'MPT (Physiotherapy)',
      'BOT (Occupational Therapy)',
      'BSc Biotechnology',
      'BSc Microbiology',
      'BSc Biochemistry',
      'BSc Zoology',
      'BSc Botany',
      'BSc Plant Biology / Plant Biotechnology',
      'BSc Genetics',
      'BSc Bioinformatics',
      'BSc Life Sciences',
      'BSc Nutrition & Dietetics',
      'BSc Food Science / Food Technology',
      'BSc Home Science',
      'BSc Chemistry',
      'BSc Medical Lab Technology (MLT)',
      'BSc Radiology / Imaging Technology',
      'BSc Cardiac / Perfusion Technology',
      'BSc Operation Theatre & Anaesthesia Technology',
      'BSc Optometry',
      'BSc Dialysis Technology',
      'BSc Respiratory Therapy',
      'BSc Physician Assistant',
      'BSc Emergency Medical Technology',
      'BSc Medical Records / Health Information Mgmt',
      'BSc Audiology & Speech Language Pathology',
      'BSc Psychology',
      'BSc Forensic Science',
      'BSc Agriculture / Horticulture',
      'BVSc (Veterinary Science)',
      'BSc Fisheries',
      'BTech / BE Biotechnology / Biomedical',
      'MSc Biotechnology / Microbiology / Biochemistry',
      'MSc Zoology / Botany / Life Sciences',
      'MPH (Public Health) / MHA (Hospital Admin)',
      'DMLT / Paramedical Diploma',
      'Other Life Science'
    ]
  },
  {
    group: 'non-life',
    title: 'Non-Life Science',
    options: [
      'BSc Computer Science',
      'BSc Information Technology',
      'BCA',
      'MCA',
      'BSc Mathematics',
      'BSc Physics',
      'BSc Statistics',
      'BSc Electronics',
      'BSc Visual Communication',
      'BSc Hotel Management / Catering',
      'BSc Fashion Design / Costume Design',
      'BSc Geography',
      'BCom',
      'BCom (CA / Computer Applications)',
      'MCom',
      'BBA',
      'MBA',
      'BA English',
      'BA Economics',
      'BA History',
      'BA Tamil / Regional Languages',
      'BA (Other)',
      'MA (Any)',
      'BE / BTech (Engineering)',
      'ME / MTech',
      'BArch',
      'LLB (Law)',
      'BEd / MEd',
      'BSW / MSW (Social Work)',
      'Diploma / Polytechnic',
      'ITI',
      'Other Non-Life Science'
    ]
  },
  {
    group: 'school',
    title: 'School / Other',
    options: ['12th (HSC) - Biology', '12th (HSC) - Non-Biology', '10th (SSLC)', 'Other']
  }
];
